### ISSUE TITLE
Create teads-curve model

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/ief#101]
**What**: A model that returns an estimate of energy based on the generalized TEADs power curve and a TDP value.
**Why**: So we can model using the TEADs power curve.
**DoD**:
- [x] Does the model meet the specification?
- [x] Does the model have complete test coverage, including edge cases, happy path and error cases?
- [x] Is the code documented?

## Config
- `tdp`: in config or observations, this is the max watts of a chip at 100% utilization.

## Inputs
- `timestamp`
- `duration`
- `cpu`: utilization 

## Outputs
- `energy`: kWh

## Behavior
These are hardcoded teads power curve coefficients, as can be found here: https://medium.com/teads-engineering/building-an-aws-ec2-carbon-emissions-dataset-3f0fd76c98ac

| util | coeff |
| ---- | ----- |
| Idle | 0.12  |
| 10   | 0.32  |
| 50   | 0.75  |
| 100  | 1.02  |

coeff = using a spline to fine the right coeff based of the passed in utilization.
energy = tdp * coeff * duration (in kWh)

### Input

```yaml
observations: 
  - timestamp: 2023-07-06T00:00
    duration: 3600
    cpu: 50
```

### Output

```yaml
impacts: 
  - timestamp: 2023-07-06T00:00
    tdp: 100
    duration: 3600
    cpu: 50
    energy: 0.075 # kwh
```
