### ISSUE TITLE
Model Plugin - sci-m

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/ief#119]
- **What**: A model plugin to represent the embodied calculation in an SCI equation.
- **Why**: So we can calculate an SCI calculation pipeline
- **DoD**:
- [x] Does the model meet the specification?
- [x] Does the model have complete test coverage, including edge cases, happy path and error cases?
- [x] Is the code documented?
- [x] Has the units.yml been updated with any new params for this model?
- [ ] Has at least one example impl file been generated?

## Config
N/A

## Observation Params
_List the variables this model expects in an input observation_
- `te` or `total-embodied`: Total embodied emissions of some underlying hardware.
- `tir` or `time-reserved`: The length of time the hardware is reserved for use by the software.
- `el` or `expected-lifespan`:  The anticipated time that the equipment will be installed.
- `rr` or `resources-reserved`: The number of resources reserved for use by the software. (e.g. number of vCPUs you are using)
- `tor` or `total-resources`: The total number of resources available (e.g. total number of vCPUs for underlying hardware)

## Impact Params
_List the variables this model exports out as an impact_
- `embodied`: The embodied carbon emissions for this hardware in gCO2eq.

## Behavior
What does the model do to turn the observations into impacts? List any important equations or references.
- This model implements the spec as per the SCI here: https://github.com/Green-Software-Foundation/sci/blob/dev/SPEC.md#embodied-emissions
- All the params as per the Observation Params are required and pumped into this equation `M = TE * (TiR/EL) * (RR/ToR)`
- **NOTE**: An Observation Param can also point to another field in the Observation where the value should be taken, e.g. if the `time-reserved` was the string `"duration"` instead of some numerical value. Then get the value of `duration` in the observation and use that as the value for this param instead.

## Assumptions
What are the core assumptions this model makes?
- That you are calculating an SCI score.

## Limitations
In what situations is this model limited in it's function, behavior's, accuracy etc...
- N/A

## Example
Provide at least one example of some input config and observations. This is in pimpl format not rimpl format, so the config is the global config and all parameters must be present on the observation.

### Input

```yaml
observations: 
  - timestamp: 2023-07-06T00:00
    duration: 3600
    te: 458 
    tir: "duration"
    el: 126144000
    rr: 1
    tor: 1 
```

### Output

```yaml
config:
 key: value
observations: 
  - timestamp: 2023-07-06T00:00
    duration: 3600
    te: 458000 
    tir: "duration"
    el: 126144000
    rr: 1
    tor: 1 
impacts: 
  - timestamp: 2023-07-06T00:00
    duration: 3600
    te: 458000 
    tir: "duration"
    el: 126144000
    rr: 1
    tor: 1 
    embodied: 13.07
```
