### ISSUE TITLE
Model Plugin - sci-o

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/ief#120]
- **What**: Calculate operational emissions as per the SCI spec
- **Why**: So we can calculate operational emissions from energy consumption
- **DoD**:
- [x] Does the model meet the specification?
- [x] Does the model have complete test coverage, including edge cases, happy path and error cases?
- [ ] Is the code documented?
- [ ] Has the units.yml been updated with any new params for this model?
- [ ] Has at least one example impl file been generated?

## Config
- N/A 

## Observation
_List the variables this model expects in an input observation_
- `grid-ci`: The grid carbon intensity for this time, duration and region in gCO2e/kWh.
- `energy`: The number of kWh consumed in this observation.

## Impacts
_List the variables this model exports out as an impact_
- `operational-emissions`: As per the SCI spec https://github.com/Green-Software-Foundation/sci/blob/dev/SPEC.md#operational-emissions in gCO2e.

## Behavior

Multiplies `grid-ci` with `energy` to generate `operational-emissions`

## Assumptions
What are the core assumptions this model makes?
- That it's calculating an SCI score.

## Limitations
In what situations is this model limited in it's function, behavior, accuracy etc...
- N/A

## Example
Provide at least one example of some input config and observations. This is in pimpl format not rimpl format, so the config is the global config and all parameters must be present on the observation.

### Input

```yaml
observations: 
  - timestamp: 2023-07-06T00:00
    duration: 3600
    grid-ci: 100
    energy: 0.1
```

### Output

```yaml
observations: 
  - timestamp: 2023-07-06T00:00
    duration: 3600
    grid-ci: 100
    energy: 0.1
impacts: 
  - timestamp: 2023-07-06T00:00
    duration: 3600
    grid-ci: 100
    energy: 0.1
    operational-emissions: 10
```
