### ISSUE TITLE
Model Plugin - cloud-instance-metadata

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/ief#132]
- **What**:  A model which given some input params regarding cloud instances returns information useful to downstream models for computation
- **Why**: So every model doesn't need to replicate cloud instance lookups
- **DoD**:
- [ ] Does the model meet the specification?
- [ ] Does the model have complete test coverage, including edge cases, happy path and error cases?
- [ ] Has documentation been written for someone writing an IMPL using this model?
- [ ] Has the `units.yml` been updated to take into consideration the params used in this model

## Config
- `variable`: If this variable is present in the top level config what behaviour does it trigger? What is the default value if none is provided?

## Observation
_List the variables this model expects in an input observation_
- `cloud-vendor`: Unique id of the cloud vendor, e.g. "aws"
- `cloud-region`: Region as per that cloud vendors definition, e.g. "us-west"
- `cloud-instance-type`: Id of that cloud instance for that vendor, e.g. "t1.micro"

## Impacts
_List the variables this model exports out as an impact_
- `physical-processor`: The name of the underlying physical processor, family, generation.
- `vcpus-allocated`: The number of vCPU's allocated to this instance.
- `vcpus-total`: The number of vCPUs available to the underlying physical server.

## Behavior
What does the model do to turn the observations into impacts? List any important equations or references.
- For every cloud provider given an instance type tries to determine some common information for use by other models.
- We want this data source to be incredibly up to date so it need to read from the latest data, e.g. APIs from the cloud providers or some regularly export CSV.
- This will first require a lot of investigation and analysis for where and how to get the data. This might be one source https://github.com/vantage-sh/ec2instances.info/blob/master/ec2.py but we need to investigate others

## Assumptions
What are the core assumptions this model makes?
- That we have information for every instance type.
- That all we care about right now is CPU's (we need to think about Mem and GPUs as well)

## Limitations
In what situations is this model limited in it's function, behaviour, accuracy etc...
- It needs to be upto date, **don't** use the 2 year old teads model data. All modern instance types need to be supported and instance types change.

## Example
Provide at least one example of some input config and observations. This is in pimpl format not rimpl format, so the config is the global config and all parameters must be present on the observation.

### Input

```yaml
observations: 
  - timestamp: 2023-07-06T00:00
    duration: 3600
    cloud-vendor: aws
    cloud-region: us-west
    cloud-instance-type: t3.micro
```

### Output

```yaml
observations: 
  - timestamp: 2023-07-06T00:00
    duration: 3600
    cloud-vendor: aws
    cloud-region: us-west
    cloud-instance-type: t3.micro
impacts: 
  - timestamp: 2023-07-06T00:00
    duration: 3600
    cloud-vendor: aws
    cloud-region: us-west
    cloud-instance-type: t3.micro
    physical-processor: Intel Skylake E5 2686 v5
    vcpus-allocated: 2
    vcpus-total: 24
```
