### ISSUE TITLE
enable updating of `observations` from inside a model plugin

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/ief#221]
## The problem
Currently, running a model plugin can *only* add information to the `impacts` field of an `ompl`. However, to support automated observation gathering, for example from Azure monitor API or the GCP/AWS equivalents, we need the ability for a model to populate `observations` in the `impl`.

## The solution
Develop `rimpl`'s `supercomputer` component to recognize when a model is an observation importer and allow it to add data to the observations field.

## Additional concern
Observation importers will need to add multiple 'blocks' of observations representing individual timestamps, for example an API response looking as follows:

```
{[{"timeStamp":"2023-10-24T12:21:00Z", "Percentage CPU": 30},{"timeStamp":"2023-10-24T12:22:00Z", "Percentage CPU": 40},{"timeStamp":"2023-10-24T12:23:00Z", "Percentage CPU": 50}]}
```
would have to translate to the following syntax in the given `impl`:
```yaml
observations:
    - timestamp: 2023-10-24T12:21:00Z
      cpu-util: 30
    - timeStamp: 2023-10-24T12:22:00Z
      cpu-util: 40
    - timeStamp: 2023-10-24T12:23:00Z
      cpu-util: 50
```
There would also be additional info (`duration` etc) added to each observation from the model config.
