### ISSUE TITLE
Create Boavizta SCI CPU IMP

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/ief#66]
## Name 
bovizta.cpu.sci

## Model
- Create an IMP to represent the Boavizta Component Model see https://doc.api.boavizta.org/Reference/component_route/ specifically for a CPU
- Calculates the emissions associated with the use of a specific CPU, e.g. Intel XEON, Graviton etc...
- Returns the data in an SCI Impact Metric (just E and M for now)

## Model Params
The IMM takes several inputs in the raw form

### `model` 

This is the type of chip so one call to the API will only return data for ONE type of chip.

```
{
   "core_units": 24, # this is the number of cores the utilization rate is refereeing to. A utilization of 100% on a 24 core system means you're using all 24 cores 100%.
   "name": "Intel Xeon Gold 6138f", # The specific CPU this refers to.
}
```
### `usage`

```
"days_use_time": 1,         # duration in days/hours/mins
"time_workload": 50,      # %age util during that duration
"usage_location": "FRA", # region
```

### other

- verbose
- allocation (linear/total)

## Example YAML

```yaml
  - component: 
      model: 
        path: bovizta.cpu.sci
      config: 
        verbose: true
        allocation: total
        name: Intel Xeon Gold 6138f
        core_units: 24
      observations:
        shared:
          location: FRA                                    # usage_location
        series:
            -   datetime: 2023-07-06T00:00
                duration: 15s                               # translated into days_use_time
                cpu: 0.34                                      # translated into time_workload                          
            -   datetime: 2023-07-06T00:15
                duration: 15s                              
                cpu: 0.12                                    
            -   datetime: 2023-07-06T00:30
                duration: 15s                               
                cpu: 0.01                                     
            -   datetime: 2023-07-06T00:40
                duration: 15s                               
                cpu: 0.78            
```

## Observations

- Will be in the format of CPU utilization, durations.
- They additionally have a location which is either used to give more accurate embodied or if it's used for grid emissions we can ignore since we want to handle grid emissions ourselves.

### Multiple Observations

```yaml
series:
    -   datetime: 2023-07-06T00:00
        duration: 15s                             
        cpu: 0.34                                    
    -   datetime: 2023-07-06T00:15
        duration: 15s                              
        cpu: 0.12                                    
    -   datetime: 2023-07-06T00:30
        duration: 15s                               
        cpu: 0.01                                     
    -   datetime: 2023-07-06T00:40
        duration: 15s                               
        cpu: 0.78                                     
```

- We need to call the API multiple times, **once** per observation.
- Then sum up the outputs into **one** Impact Metric.
- Perhaps we provide our own "debug" mode which 

**Eventually**, we will need to convert the Energy numbers that are returned into Carbon with our own Grid Emissions data source that provides real-time grid emissions.

```yaml
series:
    -   datetime: 2023-07-06T00:00
        e: 123 # convert this to O with the I for this specific time and duration using own own data source of grid emissions
        m: 34               
    -   datetime: 2023-07-06T00:15
        e: 12 # convert this to O with the I for this specific time and duration
        m: 34                           
    -   datetime: 2023-07-06T00:30
        e: 13 # convert this to O with the I for this specific time and duration
        m: 34                            
    -   datetime: 2023-07-06T00:40
        e: 234 # convert this to O with the I for this specific time and duration
        m: 34                                 
```

## Outputs

This is the raw output from Boavizta

```json
{
  "gwp": {
    "manufacture": 970, # embodied (m) in gCO2eq
    "use": 2100,
    "unit": "kgCO2eq"
  },
  "pe": {
    "manufacture": 13000,
    "use": 71020, # energy (e) in kWh
    "unit": "MJ"
  },
  "adp": {
    "manufacture": 0.15,
    "use": 0.000354,
    "unit": "kgSbeq"
  }
}
```

ImpactMetric (SCI style) will look like so for **now**:

```
{
 'e': xxx
 'm': xxx
}
```

## Unit Tests

- Calling with observations calls the API and returns a value for **e** and **m**.
- Call with a single observation returns a single impact metric with the same timestamp and duration.
- Call with multiple observations returns a multiple impact metrics with the same timestamp and duration as the original observation.
- If you don't provide mandatory inputs it returns an error (please decide what the mandatory inputs are in terms of config and observations).
- When the Boavizta API doesn't work (400/500 whatever) it returns an error.
- If you provide an cpu name type that isn't supported, returns an error

**Comment by gnanakeethan** [comment]
@jawache  

Can you give me an explanation on 

```yaml
series:
    -   datetime: 2023-07-06T00:00
        e: 123 # convert this to O with the I for this specific time and duration using own own data source of grid emissions
        m: 34               
    -   datetime: 2023-07-06T00:15
        e: 12 # convert this to O with the I for this specific time and duration
        m: 34                           
    -   datetime: 2023-07-06T00:30
        e: 13 # convert this to O with the I for this specific time and duration
        m: 34                            
    -   datetime: 2023-07-06T00:40
        e: 234 # convert this to O with the I for this specific time and duration
        m: 34   
```

should the calculate endpoint return an array sorted by the datetime?
