### ISSUE TITLE
Create Boavizta SCI Cloud IMP

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/ief#68]
## Name 
bovizta.cloud.sci

## Scope
This model returns the SCI score and component E, I and M values for cloud providers as supported by the Boavizta API

## References
- https://doc.api.boavizta.org/Reference/cloud_route/

## Assumptions
N/A

##  Limitations
- The Boavizta API currently only supports a provider of AWS for this model.

## Validations

- List of allowed country codes: https://api.boavizta.org/docs#/utils/utils_get_all_countries_v1_utils_country_code_get
- List of supported providers: https://api.boavizta.org/docs#/cloud/server_get_all_provider_name_v1_cloud_all_providers_get
- List of supported instance_types: https://api.boavizta.org/docs#/cloud/server_get_all_archetype_name_v1_cloud_all_instances_get

## Inputs
- provider: The name of the cloud provider
- instance_type: The instance type of the VM offering on that cloud provider.
- usage_location: The location where the VM is based
- days_use_time: Fraction of a day the VM is used for.
- time_workload: Average CPU utilization for that duration **or** a breakdown of the CPU utilization for that duration in this format:
  - Array of {
        "time_percentage": % of time,
        "load_percentage": utilization for this time slice
      },
      {
        "time_percentage": % of time,
        "load_percentage": utilization for this time slice
      }
- verbose: true/false
- allocation: Method of calcualtion, linear or total

## Example IMPL

```yaml
- component: 
    model: 
      path: bovizta.cloud.sci
    config: 
      verbose: true
      allocation: total
      provider: aws
      instance_type: r6g.medium
    observations:
      shared:
        location: FRA  # usage_location
      series:
          -   datetime: 2023-07-06T00:00
              duration: 15 # translated into days_use_time
              cpu: 0.34  # translated into time_workload                          
          -   datetime: 2023-07-06T00:15
              duration: 15s                              
              cpu: 0.12                                    
          -   datetime: 2023-07-06T00:30
              duration: 15s                               
              cpu: 0.01                                     
          -   datetime: 2023-07-06T00:40
              duration: 15s                               
              cpu: 0.78            
```

## Observations

- Will be in the format of CPU utilization, durations.
- They additionally have a location which is either used to give more accurate embodied or if it's used for grid emissions we can ignore since we want to handle grid emissions ourselves.

### Multiple Observations

```yaml
series:
    -   datetime: 2023-07-06T00:00
        duration: 15s                             
        cpu: 0.34                                    
    -   datetime: 2023-07-06T00:15
        duration: 15s                              
        cpu: 0.12                                    
    -   datetime: 2023-07-06T00:30
        duration: 15s                               
        cpu: 0.01                                     
    -   datetime: 2023-07-06T00:40
        duration: 15s                               
        cpu: 0.78                                     
```

- We need to call the API multiple times, **once** per observation.

**Eventually**, we will need to convert the Energy numbers that are returned into Carbon with our own Grid Emissions data source that provides real-time grid emissions.

```yaml
series:
    -   datetime: 2023-07-06T00:00
        e: 123 # convert this to O with the I for this specific time and duration using own own data source of grid emissions
        m: 34               
    -   datetime: 2023-07-06T00:15
        e: 12 # convert this to O with the I for this specific time and duration
        m: 34                           
    -   datetime: 2023-07-06T00:30
        e: 13 # convert this to O with the I for this specific time and duration
        m: 34                            
    -   datetime: 2023-07-06T00:40
        e: 234 # convert this to O with the I for this specific time and duration
        m: 34                                 
```

## Outputs

This is the raw output from Boavizta

```json
{
  "gwp": {
    "manufacture": 970, # embodied (m) in gCO2eq
    "use": 2100,
    "unit": "kgCO2eq"
  },
  "pe": {
    "manufacture": 13000,
    "use": 71020, # energy (e) in kWh
    "unit": "MJ"
  },
  "adp": {
    "manufacture": 0.15,
    "use": 0.000354,
    "unit": "kgSbeq"
  }
}
```

ImpactMetric (SCI style) will look like so for **now**:

```
{
 'e': xxx
 'm': xxx
}
```

## Unit Tests

- Calling with observations calls the API and returns a value for **e** and **m**.
- Call with a single observation returns a single impact metric with the same timestamp and duration.
- Call with multiple observations returns a multiple impact metrics with the same timestamp and duration as the original observation.
- If you don't provide mandatory inputs it returns an error (please decide what the mandatory inputs are in terms of config and observations).
- When the Boavizta API doesn't work (400/500 whatever) it returns an error.
- If you provide an instance type that isn't supported, returns an error
- If you provide a provider that isn't supported returns an error.
- If you provide a region that isn't supported returns an error.
