### ISSUE TITLE
Create CCF Cloud SCI IMP

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/ief#71]
## Name 
ccf.cloud.sci

## Scope
This model returns the SCI score and component E, I and M values for cloud providers as supported by the CCF Package

## References
- https://github.com/cloud-carbon-footprint/ccf-coefficients/tree/main/data
- https://github.com/cloud-carbon-footprint/ccf-coefficients/blob/main/output/coefficients-aws-use.csv

## Assumptions
N/A

##  Limitations
- This is raw data, the modules on npm don't include this data and are much higher level (focusing on converting billing data and directly connecting to cloud providers)

## Validations

N/A

## Inputs

- provider: The name of the cloud provider
- instance-type: The instance type of the VM offering on that cloud provider.
- location: The location where the VM is based
- duration: Fraction of a day the VM is used for.
- utilization: Average CPU utilization for that duration

## Methodology

- We will have to build our **own** model using the raw data from the CCF coefficients repo.
- This gives the min/max watts per microarchitecture (per vCPU I presume) https://github.com/cloud-carbon-footprint/ccf-coefficients/blob/main/output/coefficients-aws-use.csv
- This gives it seems a breakdown of all the instance types in AWS and some values for the powercurve for each instance type: https://github.com/cloud-carbon-footprint/ccf-coefficients/blob/main/data/aws-instances.csv
- These scripts might give some indication regarding how the calculations are done. https://github.com/cloud-carbon-footprint/ccf-coefficients/tree/main/ccfcoef

## Example IMPL

```yaml
- component: 
    model: 
      path: ccf.cloud.sci
    config: 
      provider: aws
      instance_type: r6g.medium
    observations:
      series:
          -   datetime: 2023-07-06T00:00
              duration: 15 # translated into days_use_time
              cpu: 0.34  # translated into time_workload                          
          -   datetime: 2023-07-06T00:15
              duration: 15                              
              cpu: 0.12                                    
          -   datetime: 2023-07-06T00:30
              duration: 15                               
              cpu: 0.01                                     
          -   datetime: 2023-07-06T00:40
              duration: 15                               
              cpu: 0.78            
```

## Observations

- Will be in the format of CPU utilization, durations.

## Outputs

ImpactMetric (SCI style) will look like so for **now**:

```
{
 'e': xxx
 'm': xxx
}
```

## Unit Tests

- Calling with observations calls the API and returns a value for **e** and **m**.
- Call with a single observation returns a single impact metric with the same timestamp and duration.
- Call with multiple observations returns a multiple impact metrics with the same timestamp and duration as the original observation.
- If you don't provide mandatory inputs it returns an error (please decide what the mandatory inputs are in terms of config and observations).
- When the Boavizta API doesn't work (400/500 whatever) it returns an error.
- If you provide an instance type that isn't supported, returns an error
- If you provide a provider that isn't supported returns an error.
- If you provide a region that isn't supported returns an error.
