### ISSUE TITLE
Create pimpl.py to run model plugin impls

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/ief#84]
**What**: Create a command line tool called pimple.py to load and compute just one model plugin and not a whole graph
**Why**: So we can test each model plugin individually without needing to specific a whole graph and so we can create a language agnostic interface to model plugins (the shell)
**SoW**:
- [x] Create a python script in the bin folder.
- [x] It must load up the impl related to just one component/model, as per the spec.
- [x] It must parse the content, call the model once's per observation and export the same file but with an extra impacts node, one impact metric per observation.
- [x] It must take params in the form of parameters to the scripts and also in the form of STDIN and STDOUT.
- [x] It must be able to surface errors.

This is going to be linked to this task https://github.com/Green-Software-Foundation/ief/issues/83 through both these tasks we'll be able to run a model written in python through an engine written in typescript.

So it takes in a file of this format:

```yaml
    config: 
      <key>: <value>
    observations:
        - timestamp: <timestamp>
          duration: <duration>
          <key>: <value>
        - timestamp: <timestamp>
          duration: <duration>
          <key>: <value>  
```

and outputs a file of this format

```yaml
    config: 
      <key>: <value>
    observations:
        - timestamp: <timestamp>
          duration: <duration>
          <key>: <value>
        - timestamp: <timestamp>
          duration: <duration>
          <key>: <value>  
    impacts:
        - timestamp: <timestamp>
          duration: <duration>
          <key>: <value>
        - timestamp: <timestamp>
          duration: <duration>
          <key>: <value>  
```
