### ISSUE TITLE
Standardize observation params

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/ief#89]
**What**: A configuration file that defines the name, the default units and other metadata for observation and impact metric params.
**Why**: So we can standardize language and expectations across all imps and the consumers of the framework.
**SoW**:
- When you see the word `cpu` in an observation list, it should be clear that this is for CPU utilization, the default units is percentage and to aggregate you average two utilizations, for things like carbon when you aggregate you sum them up.
- [ ] Create an IEF configuration file easy to find and refer to by all consumers of IEF that standardized these values.
- [ ] Make all existing IMPs and code adhere to this standard.

Example:

```yaml
cpu:
  description: refers to CPU utilization.
  unit: percentage
  aggregation: avg
carbon:
  description: an amount of carbon emitted into the atmosphere
  unit: gCO2e
  aggregation: sum
```
